#ifndef CONFIG_USER_H
#define CONFIG_USER_H


#define RGBLIGHT_SLEEP
#define AUTO_SHIFT_TIMEOUT 150
// #define NO_AUTO_SHIFT_SPECIAL
// #define NO_AUTO_SHIFT_NUMERIC
// #define NO_AUTO_SHIFT_ALPHA
#endif